apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/mostlydevops/wordsmith-api
  newTag: latest
- name: ghcr.io/mostlydevops/wordsmith-web
  newTag: latest
configMapGenerator:
- files:
  - words.sql
  name: db-schema
resources:
- ../../base
- ./web-ingress.yaml
