apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: bretfisher/wordsmith-web
  newName: ghcr.io/mostlydevops/wordsmith-web
  newTag: stable-20230714-fc211cb
- name: bretfisher/wordsmith-api
  newName: ghcr.io/mostlydevops/wordsmith-api
  newTag: stable-20230714-8c5f603
configMapGenerator:
- files:
  - words.sql
  name: db-schema
resources:
- ../../base
