apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: bretfisher/wordsmith-api
  newTag: latest
- name: bretfisher/wordsmith-web
  newTag: latest
- name: ghcr.io/bretfisher/docker-build-workflow
  newTag: gha-4649691147
configMapGenerator:
- files:
  - words.sql
  name: db-schema
resources:
- ../../base
