apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: bretfisher/wordsmith-api
  newName: ghcr.io/mostlydevops/wordsmith-api
  newTag: 20230422-896efd5
- name: bretfisher/wordsmith-web
  newName: ghcr.io/mostlydevops/wordsmith-web
  newTag: 20230422-6c275d1
- name: ghcr.io/mostlydevops/wordsmith-web-stable
  newTag: stable-20230719-063b3a6
configMapGenerator:
- files:
  - words.sql
  name: db-schema
resources:
- ../../base
