apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/mostlydevops/wordsmith-api-stable
  newTag: latest
- name: ghcr.io/mostlydevops/wordsmith-web-stable
  newTag: 20230422-6c275d1
